### ISSUE TITLE
Self-added third-party keys are not scraped

### ISSUE THREAD

**Issue by GMMan** [GMMan/GroupeesDownload#7]
Not sure if this matters to anyone, but any third-party keys you add yourself won't be scraped due to them not appearing in the bundles list. I don't think it matters much because you should have the original key anyway, but if anyone will find this useful, please comment or react and I may implement it.

**Comment by Sleazus** [comment]
Hi, this would be very useful for me. Would love it if you could implement it.
Just wondering does the program tell you which keys are used or is there an option to list only unused keys?
Also does it tell you how much space you need for your downloads?

**Comment by GMMan** [comment]
> Just wondering does the program tell you which keys are used or is there an option to list only unused keys?

Key status is included in the export.
> Also does it tell you how much space you need for your downloads?

No
> Does it download other? like comic bundles?

It downloads all file types.
> Could it scrap all the revealed keys first and then make another ist of the newly revealed keys?

You can export keys before revealing and after revealing, and perform a diff yourself.

**Comment by sbenrap** [comment]
GMMan - That type of feature could be really useful for me. Over the years I turned Groupees into the main way I trade games due to its convenience, I think I have a few hundred keys from various other bundles there and I didn't track them any other way :(

If it's not too much effort I would be really grateful if you could scrape those keys (even just to get the games themselves) so that I may put them onto some spreadsheet.

Big thanks!

**Comment by GMMan** [comment]
Implemented in 5c499ad5368cd6f9f90601f408f94be42a3b28a4
